server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      # 跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      # 路由
      routes:
        - id: user-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/users/**, /friend/**
        - id: chat-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/chat-messages/**, /ws/**, /chat/**