server:
  port: 8082

spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.17.101:3306/chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql_2S7imn

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chat.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
